// src/components/About/AboutVisionMissionValues.tsx
import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useTheme } from "../../context/ThemeContext";
import { Eye, Target, HeartHandshake, Trophy, Star, X } from "lucide-react";

const AboutVisionMissionValues = () => {
  const { theme } = useTheme();
  const isDark = theme === "dark";
  const [isModalOpen, setIsModalOpen] = useState(false);

  const sections = [
    {
      title: "Our Vision",
      icon: Eye,
      gradient: "from-mg-gold to-yellow-600",
      desc: "To birth a new era of African financial sovereignty — where every Ghanaian trader, from the bustling markets of Accra to the quiet streets of Tamale, stands tall on the global stage. We see a nation of millionaires built not on hope, but on mastery, discipline, and fearless execution.",
      highlight: "Ghana Will Lead the World in Trading Excellence.",
      image: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
      fullContent: {
        title: "The Full Vision",
        body: `
          <p class="text-lg leading-relaxed mb-6">We envision a Ghana where forex trading is not a gamble — but a <span class="text-mg-green font-bold">national skill</span>. Where every university graduate, market woman, and young hustler has access to institutional-grade education.</p>
          
          <p class="text-lg leading-relaxed mb-6">We see <span class="text-mg-gold font-bold">10,000+ funded traders</span> from Ghana alone. We see Ghanaian strategies taught in London, New York, and Dubai. We see the <span class="text-mg-green">Black Star</span> on every global trading leaderboard.</p>
          
          <ul class="space-y-4 mb-8">
            <li class="flex items-center gap-3"><Star className="w-5 h-5 text-mg-gold" /> 1 in 10 Ghanaians financially free by 2030</li>
            <li class="flex items-center gap-3"><Star className="w-5 h-5 text-mg-gold" /> Ghana as Africa’s #1 forex education hub</li>
            <li class="flex items-center gap-3"><Star className="w-5 h-5 text-mg-gold" /> $1B+ in profits generated by our students</li>
          </ul>
          
          <p class="text-xl font-bold text-mg-green italic">This is not a dream. This is the plan.</p>
        `,
        image: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=90"
      },
      delay: 0.2
    },
    // Mission & Values remain as before (no modal)
    {
      title: "Our Mission",
      icon: Target,
      gradient: "from-mg-green to-emerald-700",
      desc: "To train 100,000 African traders in the art of pure price action — no indicators, no bots, no noise. We deliver institutional-grade strategies, live trade execution, and psychological armor so you don’t just survive the markets — you dominate them.",
      highlight: "We Don’t Teach Theory. We Forge Winners.",
      image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
      delay: 0.4
    },
    {
      title: "Our Values",
      icon: HeartHandshake,
      gradient: "from-red-600 to-orange-700",
      desc: "Precision in every pip. Discipline in every decision. Hustle in every dawn. Integrity in every trade. Community in every win. We are not a school — we are a brotherhood of warriors, forged in the fire of real markets, bound by Ghanaian grit and global ambition.",
      highlight: "Built on Black Star Blood. Fueled by Victory.",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
      delay: 0.6
    },
  ];

  return (
    <>
      <section className={`py-32 relative overflow-hidden ${isDark ? "bg-gradient-to-b from-mg-black via-mg-charcoal to-black" : "bg-gradient-to-b from-mg-light-bg via-white to-mg-light-bg"}`}>
        {/* Ghana Flag Stripe + Black Star */}
        <div className="absolute top-0 left-0 w-full h-5 bg-gradient-to-r from-red-600 via-yellow-500 to-green-600 shadow-2xl z-20" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-7 h-7 -mt-0.5 z-30">
          <svg viewBox="0 0 100 100" className="w-full h-full drop-shadow-xl">
            <path d="M50 10 L61.8 35.5 L88.2 38.6 L67.7 56.4 L71.8 82.8 L50 69.5 L28.2 82.8 L32.3 56.4 L11.8 38.6 L38.2 35.5 Z" fill="#000" stroke="#000" strokeWidth="3" />
          </svg>
        </div>

        {/* Golden Glow */}
        <motion.div
          className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,215,0,0.08)_0%,transparent_70%)]"
          animate={{ opacity: [0.4, 0.7, 0.4] }}
          transition={{ duration: 8, repeat: Infinity }}
        />

        <div className="relative z-10 max-w-7xl mx-auto px-6">
          {/* CATCHY HEADER */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 1, type: "spring", stiffness: 80 }}
            className="text-center mb-24"
          >
            <h1 className={`text-5xl md:text-7xl font-black tracking-tight mb-6 leading-tight`}>
              <span className={`block ${isDark ? "text-mg-gold" : "text-mg-charcoal"}`}>This Is Not a Dream.</span>
              <span className="block text-mg-green text-6xl md:text-8xl">
                This Is <span className="underline decoration-mg-gold decoration-4">Destiny</span>.
              </span>
            </h1>
            <p className={`text-xl md:text-2xl max-w-4xl mx-auto font-medium ${isDark ? "text-mg-paper/80" : "text-mg-charcoal/80"}`}>
              Vision. Mission. Values. — Forged in Ghana. Proven in the Markets.
            </p>
          </motion.div>

          {/* ALTERNATING LAYOUT */}
          {sections.map((section, i) => {
            const isEven = i % 2 === 0;
            const isVision = i === 0;

            return (
              <div
                key={i}
                className={`grid md:grid-cols-2 gap-16 md:gap-20 items-center mb-32 last:mb-0 ${
                  isEven ? "md:[&>:first-child]:order-1 md:[&>:last-child]:order-2" : "md:[&>:first-child]:order-2 md:[&>:last-child]:order-1"
                }`}
              >
                {/* IMAGE */}
                <motion.div
                  initial={{ opacity: 0, x: isEven ? -60 : 60 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: section.delay + 0.1, type: "spring", stiffness: 70 }}
                  className="relative group"
                >
                  <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-mg-gold/20 to-mg-green/20 blur-3xl scale-95 group-hover:scale-100 transition-transform duration-700 -z-10" />
                  <img
                    src={section.image}
                    alt={section.title}
                    className="w-full h-96 md:h-[520px] object-cover rounded-3xl shadow-2xl border-4 border-mg-gold/30 group-hover:border-mg-gold/60 group-hover:scale-[1.02] transition-all duration-700"
                  />
                  <div className="absolute inset-0 rounded-3xl bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none" />
                </motion.div>

                {/* TEXT */}
                <motion.div
                  initial={{ opacity: 0, x: isEven ? 60 : -60 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: section.delay + 0.2, type: "spring", stiffness: 70 }}
                  className="space-y-8"
                >
                  <div className="flex items-center gap-5">
                    <div className={`w-20 h-20 rounded-full bg-gradient-to-br ${section.gradient} p-4 shadow-2xl`}>
                      <section.icon size={44} className="text-white" />
                    </div>
                    <h3 className={`text-4xl md:text-5xl font-black ${isDark ? "text-mg-gold" : "text-mg-charcoal"}`}>
                      {section.title}
                    </h3>
                  </div>

                  <p className={`text-lg md:text-xl leading-relaxed font-medium ${isDark ? "text-mg-paper" : "text-mg-charcoal"}`}>
                    {section.desc}
                  </p>

                  <motion.blockquote
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: section.delay + 0.4 }}
                    className="relative pl-8 border-l-4 border-mg-green"
                  >
                    <p className={`text-2xl md:text-3xl font-bold italic text-mg-green leading-tight`}>
                      “{section.highlight}”
                    </p>
                  </motion.blockquote>

                  {/* SEE MORE BUTTON — ONLY FOR VISION */}
                  {isVision && (
                    <motion.button
                      onClick={() => setIsModalOpen(true)}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.97 }}
                      className="inline-flex items-center gap-3 px-8 py-4 bg-mg-green text-white rounded-full font-bold text-lg shadow-xl hover:shadow-mg-green/50 transition-all"
                    >
                      See the Full Vision <Star size={24} />
                    </motion.button>
                  )}
                </motion.div>
              </div>
            );
          })}

          {/* FINAL CTA */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 1, duration: 0.8, type: "spring" }}
            className="mt-40 text-center"
          >
            <div className="inline-block p-12 md:p-16 rounded-3xl bg-gradient-to-br from-mg-gold via-yellow-500 to-mg-green shadow-2xl relative overflow-hidden">
              <div className="absolute inset-0 bg-black/20" />
              <Trophy size={64} className="mx-auto mb-6 text-white drop-shadow-2xl" />
              <p className="text-4xl md:text-5xl font-black text-white drop-shadow-2xl leading-tight">
                Your Legacy Starts Here
              </p>
              <p className="text-2xl md:text-3xl font-bold text-white mt-4 drop-shadow-xl">
                Trade Like a <span className="underline decoration-mg-charcoal decoration-4">MarketGod</span>
              </p>
              <motion.a
                href="/plans"
                whileHover={{ scale: 1.05, boxShadow: "0 0 40px rgba(255,215,0,0.6)" }}
                whileTap={{ scale: 0.97 }}
                className="inline-flex items-center gap-4 mt-10 px-10 py-5 bg-mg-charcoal text-mg-gold rounded-full font-bold text-xl shadow-2xl hover:shadow-mg-gold/60 transition-all"
              >
                Enroll Now — Claim Your Seat <Star size={28} />
              </motion.a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* FULL-SCREEN MODAL */}
      <AnimatePresence>
        {isModalOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/80 backdrop-blur-xl"
            onClick={() => setIsModalOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.8, opacity: 0 }}
              transition={{ type: "spring", stiffness: 300, damping: 30 }}
              className="relative max-w-5xl w-full max-h-[90vh] overflow-y-auto bg-gradient-to-br from-mg-charcoal via-black to-mg-black rounded-3xl shadow-2xl p-8 md:p-12"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Close Button */}
              <button
                onClick={() => setIsModalOpen(false)}
                className="absolute top-6 right-6 p-2 rounded-full bg-mg-gold/20 hover:bg-mg-gold/40 transition-all"
              >
                <X size={28} className="text-mg-gold" />
              </button>

              {/* Modal Header */}
              <div className="text-center mb-10">
                <h2 className="text-5xl md:text-6xl font-black text-mg-gold mb-4">
                  {sections[0].fullContent.title}
                </h2>
                <div className="w-32 h-1 bg-mg-green mx-auto" />
              </div>

              {/* Modal Image */}
              <img
                src={sections[0].fullContent.image}
                alt="Full Vision"
                className="w-full h-96 object-cover rounded-3xl shadow-xl mb-10"
              />

              {/* Modal Body */}
              <div
                className={`prose prose-lg max-w-none ${isDark ? "prose-invert" : ""}`}
                dangerouslySetInnerHTML={{ __html: sections[0].fullContent.body }}
              />

              {/* Final CTA in Modal */}
              <div className="text-center mt-12">
                <motion.a
                  href="/plans"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.97 }}
                  className="inline-flex items-center gap-4 px-10 py-5 bg-mg-green text-white rounded-full font-bold text-xl shadow-xl hover:shadow-mg-green/60 transition-all"
                >
                  Join the Vision Now <Trophy size={28} />
                </motion.a>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};

export default AboutVisionMissionValues;